
const RecommendedData = [
  {
    id: 1,
    img: "/Images/Home/rec__main--first.png",
    discount: "-30%",
    subtitle: "Omnires",
    stock: "In stock",
    number: "2123532",
    title: "Connection with a handle Omnires round",
    width: 34,
    heihgt: 45,
    depth: 45,
    price: 45.00,
    priceDiscount: 55.00,
  },
  {
    id: 2,
    img: "/Images/Home/rec__main--second.png",
    discount: "-15%",
    subtitle: "GoodHome",
    stock: "Out of stock",
    number: "129565",
    title: "Countertop washbasin GoodHome Tekapo",
    width: 32,
    heihgt: 21,
    depth: 75,
    price: 51.00,
    priceDiscount: 64.00,
  },
  {
    id: 3,
    img: "/Images/Home/rec__main--third.png",
    discount: "-15%",
    subtitle: "GoodHome",
    stock: "In stock",
    number: "833565",
    title: "Perforated Simpson tape 25 x 2500 x 2 mm",
    width: 45,
    heihgt: 12,
    depth: 35,
    price: 79.00,
    priceDiscount: 70.00,
  },
  {
    id: 4,
    img: "/Images/Home/rec__main--fourth.png",
    discount: "-15%",
    subtitle: "GoodHome",
    stock: "Out of stock",
    number: "634465",
    title: "AMBER DECOR Bulb 60W, E27 590",
    width: 45,
    heihgt: 12,
    depth: 35,
    price: 38.00,
    priceDiscount: 30.00,
  }
]

export default RecommendedData
